---
title: Stackbit Fresh Theme
baseURL: "/"
params:
  layout_style: default
  palette: orange
  header:
    title: Klan Zephyra
    tagline: ''
    profile_img: "/images/erb2.png"
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
outputs:
  home:
    - HTML
    - AMP
  page:
    - HTML
    - AMP
